django_payment/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("payment.urls", namespace="payment")),
]

payment/urls.py
from django.urls import path

from payment.views import *

app_name = "payment"

urlpatterns=[
    path("khalti/verify/", KhaltiVerifyPayment.as_view(), name="khalti_verify"),
    path("home/", home, name="home"),
    path("success/", success, name="success"),
    path("fail/", fail, name="fail"),
    path("esewa/", esewa, name="esewa"),
    path("esewa/verify/", EsewaVerifyView.as_view(), name="esewa_verify"),
]

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
from django.shortcuts import render, redirect

from django.conf import settings
import requests

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.parsers import JSONParser


class KhaltiVerifyPayment(APIView):

    # parser_classes = [JSONParser]

    def post(self, request):
        token = request.POST.get('token')
        amount = request.POST.get('amount')

        url = settings.KHALTI_VERIFY_URL
        auth_key = "Key {}".format(settings.KHALTI_SECRET_KEY)
        payload = {
        "token": token,
        "amount": amount,
        }
        headers = {
        "Authorization": auth_key
        }
        try:
            response = requests.post(url, payload, headers = headers)
            if response.status_code == 200 :
                return Response({
                    'status':"Success",
                    'details':response.json(),
                }, status=response.status_code)

            else:
                return Response({
                    'status':response.status_code,
                    'details':response.json(),
                }, status=response.status_code)

        except requests.exceptions.RequestException as e:
            return Response({
                "status": "Request error occurred",
                "details": response.json(),
            })


def esewa(request):
    return render(request, "payment/eSewa.html")


class EsewaVerifyView(APIView):

    def get(self, request, *args, **kwargs):
        import xml.etree.ElementTree as ET
        oid = request.GET.get("oid")
        amt = request.GET.get("amt")
        refId = request.GET.get("refId")
        print("------"+refId+"-----")

        url = "https://uat.esewa.com.np/epay/transrec"
        d = {
            'amt': amt,
            'scd': 'EPAYTEST',
            'rid': refId,
            'pid': oid,
        }

        response = requests.post(url, d)
        root = ET.fromstring(response.content)
        status = root[0].text.strip()
        print(response.text)
        if status == "Success":
            return redirect("payment:success")
        else:
            return redirect("payment:fail")



def fail(request):
    return render(request, "payment/fail.html")

def success(request):
    return render(request, "payment/success.html")

def home(request):
    return render(request, "payment/index.html")

payment/templates/payment/eSewa.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        #myform{
            display: none;
        }
    </style>
</head>
<body>
    <h3 style="text-align: center;">You will be redirected to the esewa website..</h3>
    <form action="https://uat.esewa.com.np/epay/main" method="POST" id="myform">
        <input value="100" name="tAmt" type="hidden">
        <input value="100" name="amt" type="hidden">
        <input value="0" name="txAmt" type="hidden">
        <input value="0" name="psc" type="hidden">
        <input value="0" name="pdc" type="hidden">
        <input value="EPAYTEST" name="scd" type="hidden">
        <input value="ee2c3ca1-696b-4cc5-a6be-2c40d928d444" name="pid" type="hidden">
        <input value="http://127.0.0.1:8000/esewa/verify/" type="hidden" name="su">
        <input value="http://127.0.0.1:8000/fail/" type="hidden" name="fu">
        <input value="Submit" type="submit">
    </form>

    <script>
        setTimeout(function(){
            document.getElementById("myform").submit()
        }, 500)
        
    </script>
</body>
</html>

payment/templates/payment/fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    Failure
</body>
</html>

payment/templates/payment/index.html
<html>
<head>
    <script
			  src="https://code.jquery.com/jquery-3.6.0.min.js"
			  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
			  crossorigin="anonymous"></script>
    <script src="https://khalti.s3.ap-south-1.amazonaws.com/KPG/dist/2020.12.17.0.0.0/khalti-checkout.iffe.js"></script>
</head>
<body>
    ...
    <!-- Place this where you need payment button -->
    <button id="payment-button">Pay with Khalti</button>
    <!-- Place this where you need payment button -->
    <!-- Paste this code anywhere in you body tag -->

    <script>

        function verifyPayment(payload) {
        $.ajax({
            url: "{% url 'payment:khalti_verify' %}",
            type: "POST",
            data: payload,
            dataType: 'json',
            success: function (response) { alert("Success") },
            error: function (error) { console.log(error.responseJSON['message']) }
        });
    }

        var config = {
            // replace the publicKey with yours
            "publicKey": "test_public_key_f39a4353f290400a9fc380a0b89e0af0",
            "productIdentity": "1234567890",
            "productName": "Dragon",
            "productUrl": "http://gameofthrones.wikia.com/wiki/Dragons",
            "paymentPreference": [
                "KHALTI",
                "EBANKING",
                "MOBILE_BANKING",
                "CONNECT_IPS",
                "SCT",
                ],
            "eventHandler": {
                onSuccess (payload) {
                    // hit merchant api for initiating verfication
                    console.log(payload);
                    verifyPayment(payload);
                },
                onError (error) {
                    console.log(error);
                },
                onClose () {
                    console.log('widget is closing');
                }
            }
        };

        var checkout = new KhaltiCheckout(config);
        var btn = document.getElementById("payment-button");
        btn.onclick = function () {
            // minimum transaction amount must be 10, i.e 1000 in paisa.
            checkout.show({amount: 1000});
        }
    </script>
    <!-- Paste this code anywhere in you body tag -->
    ...
</body>
</html>

payment/templates/payment/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    Success
</body>
</html>